project:
  type: website

website:
  title: "MS-DIAL 5 tutorial"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - lipidomics.qmd
      - metabolomics.qmd
      - proteomics.qmd
      - imaging.qmd
      - text: "Utilities"
        menu:
          - utils.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



